#ifndef BIND_CONSTANTS_H
#define BIND_CONSTANTS_H

#define BINDING_OUTPUT 0
#define BINDING_MATERIALS 1
#define BINDING_SPHERES 2
#define BINDING_PLANES 3
#define BINDING_TRIANGLES 4
#define BINDING_VERTICES 5
#define BINDING_INDICES 6

#endif  // BIND_CONSTANTS_H